### ISSUE TITLE
Typescript 2.1 Merge Types

### ISSUE THREAD

**Issue by kitsonk** [dojo/compose#101]
**Enhancement** 

Merge types are in master and should be part of TypeScript 2.1 (see: [Microsoft/TypeScript#12114](https://github.com/Microsoft/TypeScript/pull/12114)).  These will allow us to model situations like mixins (assign/deepAssign) and things like our `.setState()` in `Stateful`.

This will require changing our state interfaces to something that is not all optional and use the merge typing to model the necessary types.

Package Version: master

**Comment by dylans** [comment]
Resolved in https://github.com/dojo/interfaces/pull/54 and other work in other tickets.

**Comment by maier49** [comment]
@dylans I think there is still some work to be done on compose for this. Specifically using it to check that calls to override, and potentially extends, are valid at design time.
