### ISSUE TITLE
Consider splitting createStateful

### ISSUE THREAD

**Issue by matt-gadd** [dojo/compose#112]
**Enhancement**

At the moment `createStateful` does not allow users to leverage internal state, without also exposing the ability to externalise it also. 

This seems undesirable for widget authors who do not want to potentially expose state to a store. The api requirements for internal state and external state don't match anyway so it seems logical that these may live separately.

The simplest solution would be to reduce `createStateful` to internal state only. We can probably write another mixin for `createExternalState`.

I'm also not entirely sure why when using `fromState`, we still copy the external state to be internal, this seems like an unnecessary cost when we're essentially saying the source of truth is no longer inside.

**Comment by agubler** [comment]
This seems like a reasonable proposal; especially considering we are using compose that enables additional behaviour like external state to be added when desired via a mixin.

The change also helps facilitate a move away from `Options` as part of the API for dojo-widgets `w`, replacing that with `WidgetProperties` that mixins will be able to leverage for all trait mixins.
