### ISSUE TITLE
RxJS seems to be a peer dependency

### ISSUE THREAD

**Issue by novemberborn** [dojo/compose#32]
https://github.com/dojo/app/pull/3 uses `dojo-compose`. At the time of writing it only pulls in interfaces from `dojo-compose/mixins/createStateful`. Without the `@reactivex/rxjs` dependency installed there are errors in the `ts:dev` output:

```
Running "ts:dev" (ts) task
Compiling...
Using tsc v1.8.10
typings/globals/dojo-compose/index.d.ts(348,16): error TS2307: Cannot find module 'node_modules/@reactivex/rxjs/dist/cjs/Rx'.
typings/globals/dojo-compose/index.d.ts(465,11): error TS2305: Module ''rxjs/Rx'' has no exported member 'Observable'.
```

I think this makes RxJS a peer dependency, not a dev dependency. Which seems undesirable?

**Comment by kitsonk** [comment]
There is a typings dependency, but not a runtime code dependency, which is mildly frustrating.

The easiest way of acquiring the typings is to load them from the package, but obviously that means it has to be required.  The other thing with the `rxjs/Rx` is that I need to check to see how we can maintain these sort of "AMD" configuration.

**Comment by novemberborn** [comment]
Maybe the typings can be copied into the distribution?

**Comment by kitsonk** [comment]
If they get copied in and someone else includes them, then you will just get a raft of typings conflicts, which is a problem that is somewhat solved by typings/typings and then there are the additional changes coming in TypeScript 2 around typing acquisition.  Hopefully the issue/question I opened with `typings/typings` will help us out.

**Comment by kitsonk** [comment]
Ok, `typings/typings` is looking at this issue as a feature request, but the easiest thing to do is provide the interfaces we depend on as part of the interfaces for this package to make it self contained.  This was done via 6a8e792522d991709300ef75daed9f4872741934.
