### ISSUE TITLE
Allow `id` to be zero for stateful objects

### ISSUE THREAD

**Issue by agubler** [dojo/compose#38]
Given the following snippet within `createStateful.ts`, it prevents the `id` being `0` as it is a `falsy` value but is actually a valid `id` value.

``` js
if (id && stateFrom) {
    instance.own(instance.observeState(id, stateFrom));
}
else if (stateFrom) {
    throw new TypeError('When "stateFrom" option is supplied, factory also requires "id" option.');
}
```

**Comment by kitsonk** [comment]
Technically, `id` is typed as `string` though and `''` would not be a valid ID.  But it is understandable that values might be provided that might get coerced into a string because upstream code does not respect the typing at run-time.

**Comment by agubler** [comment]
I was being hit by this when using the MemoryStore as it auto generates an `id` based on the `data.size()` https://github.com/dojo/widgets/blob/master/src/util/createMemoryStore.ts#L256.

**Comment by kitsonk** [comment]
BAH! I expect consistency in the API? 😜
