### ISSUE TITLE
Ordering of Initialize Functions

### ISSUE THREAD

**Issue by kitsonk** [dojo/compose#42]
When mixin in a factory which has initialize functions and compose already sees that the function is in the initialize array, it will simply ignore it (e.g. not add it again).  This causes some surprising behaviour, like having to re-mixin a mixin in order to ensure that it has run before the new initialize function is run.  This means that developers have to have explicit knowledge of what mixins contain. We should consider when mixin in that we take all the initialize functions and concat them onto the end of the array but splice out any duplicates further up the stack.

**Comment by kitsonk** [comment]
This is complex topic, though I will be issuing a PR which I think provides the least surprising logic...  So given the following, you end up with the following ordering of init functions:

``` typescript
const createA = compose({}, A); // [ A ]
const createB = compose({}, B); // [ B ]
const createAB = createA.mixin(createB); // [ A, B ]
const createCAB = compose({}, C)
    .mixin({
         mixin: createAB,
         initialize: D
    }); // [ C, A, B, D ]
```

There are two major changes with this behaviour from the current, though I think only one of them will cause regressions, but I think is a better thing to do.  Previously this would have produced `[ B, A, D, C ]` which allowed people to leak expectations of subsequent mixins into `C`, which is a bad idea.  If an init function expects something from `createAB` it should only put that in `D`.  There is at least one regression in `compose` because of this and I suspect there will be others.

**Comment by kitsonk** [comment]
This is now merged.  Just a reminder that this does cause regressions in some code.  Largely it is situations where the strange ordering caused some odd workarounds, but still, this will break some things when it is released.

**Comment by agubler** [comment]
Let's release it now then 👍🏻

**Comment by agubler** [comment]
released
