### ISSUE TITLE
Support Async Initializers

### ISSUE THREAD

**Issue by kitsonk** [dojo/compose#54]
**Enhancement**

We could consider supporting async initializers where if the value returned from an initialize function is `Thenable` that the next initializer.

The only challenge with this is that the instance is returned from the factory sync and therefore if there is an async initializer, additional sync code could run against the instance before the code completes.

Changing compose to return an instance to resolve to a promise is a lot of overhead for what someone could responsibly do within the initializer though, knowing that their code will resolve async and needs to "play nicely".

The other potential solution is that there is a discreet "async" factory for compose which supports async initializers and returns a `Promise` which resolves with the instance.

**Comment by kitsonk** [comment]
@lzhoucs I would say another possible solution that @agubler and I did, but then realised it wasn't necessary was to have and event called `state:initialized` that was emitted when `Stateful` had the state and was ready.  The one use case though became unnecessary and we then removed it and that any initializer that requires to know the state would wait for that.  We also ensure that it always went out of turn, so that the other initializers would be able to be certain to register for the event, before it could be emitted.

The problem with async, is that an initializer, ideally, has little knowledge/dependency on what came before it, or what will come after it.  Otherwise you get into all sorts of messy initialization ordering issues.  The more explicit knowledge that we allow people to introduce, creates dependencies, which creates fragile code. @matt-gadd and I chatted about it a bit and ergo this issue, though neither of us liked the ramifications of it.

I could still see that the initialization might want to see if a `Thenable` is returned from and initializer before executing the next initializer, but almost then, unless we provided some sort of hook to detect that a) there was an async initializer and b) those have completed, then no one could trust an instance.

Even though I get it, I think the better pattern is that a) try to avoid async initialization where possible and b) if unavoidable, utilise patterns that allow the initiailization state of the instance to be determined externally but without baking that solution into compose.

Again, all this is just my opinion.  More than willing to continue to discuss this further.

**Comment by agubler** [comment]
@kitsonk the problem with the `state:initialized` event is that it had to be emitted on the next turn so that consumers could actually attach a listener before the event was emitted.

We could potentially offer provide a way of setting listeners for the `state:initalized` event in the objects options... The issue for why we removed the `state:initialized` event is here https://github.com/dojo/compose/issues/96.

I tend to agree with @kitsonk in that we should avoid aync initialization as much as possible and be reactive to aysnc changed post init.

**Comment by agubler** [comment]
This is no longer relevant due to changes in the widget system
