### ISSUE TITLE
Evented and Observable events

### ISSUE THREAD

**Issue by kitsonk** [dojo/compose#57]
**Enhancement:**

While our Evented events are designed to have an API that mirrors the DOM event API, it causes two major challenges:
- No concept of backpressure, or pausability of events
- Events are delivered sync

While more and more of a widgets and other Evented objects have an asynchronous lifecycle, this does make it more difficult to manage this.

We should consider potential solutions to this, for example, utilise ES Observables to deliver events, which would allow a callback to called async serially and allow interesting transformations of the events.  For example, the following would work:

``` typescript
const evented = createEvented();
const evented
    .on('foo')
    .forEach((e) => { /* do something with event */ })
    .then(() => { /* do cleanup when the observation is completed (evented destroyed) */ });
```

The biggest challenge is that there is no concept of backpressure in Observables, which means that any subscriber would need to implement the concept if required (e.g. queue up events until it is ready to process them).

One thought, we could include some helpers that would wrap the subscribers and then providing that backpressure interface.

We should also consider if breaking from the paradigm of "DOM events" would be outweigh the developer familiarity.

**Comment by kitsonk** [comment]
In the code that brought this discussion up, I expressed a worry about storing each emitted event from startup if someone wanted to consume it:

> Also, if we indiscriminately store every event just in case a listeners comes along later, we would run into a memory issue.

But @matt-gadd indicated:

> In this example (and this is actually true for a lot of event types), you would use a sliding buffer with a size of 1, you only care about the latest event for state.

Which is a decent consideration, that we would store the last emitted event by type to delivery to a subscriber, although, I could see that you wouldn't want to do this for all event types.  Would it make it challenging to configure event types?  Right now on `Evented`, it has no explicit knowledge of potential event types to be emitted and emitting an event type that has no listeners, the event simply gets abandoned.  This would seem to require an implementor of Evented pre-configure emitted events which it would wish to retain in a buffer.

Again I could see this potentially implemented as a helper "subscriber/listener" wrapper.

**Comment by kitsonk** [comment]
Another challenge has highlighted itself related to #42.  While ordering the way in the related PR fixes a lot of the "surprises" and re-mixing in mixins that are unnecessary, it does cause some challenges if that during an init function, a mixin ends up emitting an event but another, later, mixin attaches a listener for that event.

For exampling in `createStatefulChildrenMixin` we can significantly reduce the complexity of the mixing by simply adding to `createStateful` but the init function for `createStateful` picks the `state` object out of `options` and will set it and emit a `statechange` event.  All this occurs prior to the init function for `createStatefulChildrenMixin`.

I have been reticent to complicate the lifecycle of composition, but it is potential that most of this could be dealt with by creating some sort of _post init_ hook that allowed mixins to delay certain actions until they were confident that all other initialisation functions had completed.

Instead of chaining all init functions, init functions could potentially simply be allowed to return a thenable and compose would then `Promise.all()` any returned thenables before calling any post init code (but would only do this if there was a post init function).  Of course this could result in an arms race, where mixins bake logic into post init which other mixins would depend upon, thereby having to create a post post init logic 😕.

**Comment by agubler** [comment]
I don't this is an issue currently having fixed the widget lifecycle meaning there is no need for back pressure or observables. So I think we can close this?
