### ISSUE TITLE
Changes to Stateful interfaces

### ISSUE THREAD

**Issue by kitsonk** [dojo/compose#79]
There are some changes to the `Stateful` interface in the `dojo-interfaces` specfication.  Both the `state:changed` and `state:completed` event types have been renamed.  This should be reflected in the implementation of `Stateful`.

**Comment by agubler** [comment]
@kitsonk do you think that we should include these events in addition to the existing ones to maintain backwards compatibility and once they consumers have been removed, remove the deprecated events?

**Comment by kitsonk** [comment]
@agubler I want to move these to `bases/createStateful`, to help delineate that they are bases, and therefore, we can leave `mixins/createStateful` untouched and remove it once everyone has migrated.  Does that work?

**Comment by agubler** [comment]
@kitsonk we are going to add a new `base` directory for `compose`? in which case yes that's fine - I was going to add the `init` to the existing also. Perfectly happy to take the existing `createStateful` and copy to bases at the same time?

**Comment by kitsonk** [comment]
The move was covered in issue #77.

**Comment by agubler** [comment]
Ah cool, thanks @kitsonk (hadn't seen it)

**Comment by kitsonk** [comment]
and for completeness came out of #74, saying we should be more explicit about what is a "base" and what is a "mixin" and what is a "final" class

**Comment by agubler** [comment]
This has been resolved.
