### ISSUE TITLE
Additional Diagnostics

### ISSUE THREAD

**Issue by kitsonk** [dojo/compose#82]
*\* Enhancement**

In complex class compositions, it can be difficult to diagnose how certain methods are resolved and how advice is applied.  The `getInitFunctionNames()` function is useful in providing the initialization function names/ordering, but understanding how the prototype is derived as well could be really useful when certain mixins are overriding behaviour that is already there, since we have "last one wins" resolution order, sometimes it isn't obvious that this can sometimes cause the "diamond" problem.

It might make sense to provide a `getComposeMetaData()` function that would provide an object which would provide somethings like this:

``` typescript
{
    base: 
        name: 'Base',
        keys:
            {
                foo: 'string',
                bar: 'function'
            },
    },
    mixins: [ { ... }, { ... } ]
    advice: {},
    initFunctions: [ 'initBase', 'mixinA' ]
}
```

**Comment by rishson** [comment]
Could we/do we provide debugging that explicitly states when we are overriding?

e.g.
`Overriding 'x' property with value 'bar' with value 'foo' from 'y' mixin`

Stuff like this are ideal candidates for a dojo chrome dev plugin..

**Comment by kitsonk** [comment]
Right now, we do not provide anything that explicitly states that.  We debated "throwing" but overriding is a very legitimate and common use case, and sometimes desirable and sometimes unintentional.  The debate was do we have something like C3MRO, which is "magical" or are we just document the behaviour.  The latter was what was decided, but sometimes that is often hard to "see", therefore the meta data.

Personally, I would still like to expose this sort of stuff on an "on demand" process.  Given a set of meta data like the above, it would be easy to reduce it into a set of diagnostics that said "This mixin is overriding this method" and produce that information, and as suggested surface this in a dev tool in a more usable way.  Logging a "warn" or having to turn on a "debug" mode I think won't be as efficient as essentially representing this private meta data in a usable way "on demand".

**Comment by kitsonk** [comment]
Since we have deprecated this package, we should close this issue.
