### ISSUE TITLE
Events should not emit on the next turn and `state:initialized` is no longer required

### ISSUE THREAD

**Issue by agubler** [dojo/compose#96]
**Enhancement**

`state` change events should not emit on the next turn. `state:initialized` can be removed and reverted back to always emitting `state:changed` in all cases. 

The `state:initialized` event was implemented to assist with child widget management but this is no longer required with the `d` widget proposal. Having the event emitted on the next turn causes the render to called twice (in fact `n` number of times depending on how nested a widgets children are).

Package Version: Latest

**Comment by kitsonk** [comment]
There still can be a period between when creation completes and the reference to the widget is returned, but you cannot "trust" that `widget.state` is valid.  We have no way of determining that at the moment, though I can't think of a specific use case.  I guess if we really run into that issue, we could have `instance.state` return `null` until it has been properly set.
