### ISSUE TITLE
Event globbing with Evented

### ISSUE THREAD

**Issue by kitsonk** [dojo/compose#98]
**Enhancement**

We should allow registration of listeners that allow for event globbing.

Package Version: master

**Code**

```ts
import createEvented from 'dojo-compose/bases/createEvented';

const evented = createEvented();

evented.on('*', (e) => { /* all events */ });
evented.on('domain:*', (e) => { /* events starting with type 'domain:' */ });
```

**Comment by lzhoucs** [comment]
Do we want to support all glob wildcards, or just `*` for 0 or more characters? I think that compared to file path, event type name is a much simpler string, so adding support for `*` might be sufficient, util we discover more complicated use cases.
